### ISSUE TITLE
Flashing process

### ISSUE THREAD

**Issue by aortner** [nebkat/esp32-xbee#1]
hi. i have got an eary version from ardusimple.

i did follow your firmware update step by step - it did not work at me

solution: i need to press boot some times to start the flashing...

**Comment by nebkat** [comment]
Hi Andreas, did you follow the process to enter download mode by holding BOOT button + pressing RESET, and then have to press BOOT button on its own after this? Or do you mean just this initial button combination?

**Comment by aortner** [comment]
oh i see:

first: boot + reset
the boot button again ..

you should add this to your docs.. :-)

**Comment by nebkat** [comment]
Hmm, the second boot press shouldn't actually have any effect. If you just hold BOOT + press and release RESET, does it work correctly?
