### ISSUE TITLE
Compile with PlatformIO 

### ISSUE THREAD

**Issue by hagre** [nebkat/esp32-xbee#2]
Hello, I am trying to compile with PlatformIO and espidf framework, but i still have lots of errors.
I moved the /main files to the /src folder and some other small adjustments, but it is still not working.
Help needed! Has anyone a good guideline for this?

**Comment by nebkat** [comment]
Could you attach the error logs? I'm not sure how ESP-IDF works for PlatformIO, but you can also use the standard ESP-IDF build system https://docs.espressif.com/projects/esp-idf/en/latest/get-started/

**Comment by hagre** [comment]
Sorry for may late replay,
Thank you for your suggestion, I am using the standard ESP-IDF build system now. No luck and too much manual converting work for PlatformIO and VScode (problems with differnet folder structure and config files....)

**Comment by arnolde** [comment]
I only use platformio for all my projects and I would appreciate if anyone has already converted their source and would share it (or a guide howto).
