### ISSUE TITLE
ubx messages to NTRIP or socket

### ISSUE THREAD

**Issue by jubru** [nebkat/esp32-xbee#25]
Hello,

Well done for your development, it's really cool.
Currently I have 1 simpleRTK2B and 1 WiFi NTRIP Master. I easily send RTCM message to rtk2go.com with NTRIP server connection. 
But, Is it also possible to send the UBX protocol messages from F9P to NTRIP/socket server with the Wifi NTRIP MASTER (messages UBX-RXM-RAWX and UBX-RXM-SFRBX) ?
I activated this from u-center:
![image](https://user-images.githubusercontent.com/12160142/79990605-8a254e80-84b1-11ea-870e-98f6fc86d3aa.png)
and 
![image](https://user-images.githubusercontent.com/12160142/79990709-a88b4a00-84b1-11ea-8aeb-cc8cd2e9bccb.png)
but no UBX data comes out of the NTRIP MASTER

Thank you in advance
Best regards

**Comment by nebkat** [comment]
Hi @jubru,

Unfortunately the ZED-F9P doesn't support the UBX protocol via UART2, the option shown in the u-center configuration is simply to make it consistent with UART1 and potential future devices that might support the feature.

You can however disable UART2, and use jumper wires to connect the output of UART1 to UART2, and in your case you would only need to have the TX line of UART1 connected to make this work.

Best Regards,
Nebojsa

**Comment by ardusimple** [comment]
Soon we will launch a new simpleRTK2B with UART1 on the XBee socket, so this will be possible.
