### ISSUE TITLE
About the esp-idf version required for compilation.

### ISSUE THREAD

**Issue by lisn3188** [nebkat/esp32-xbee#27]
Hello author, first of all thank you for your open source
I tried to download the code and use esp-idf to compile it and got some errors in variable definition. It should be caused by the wrong idf version.
May I ask which version of esp-idf you are using?

**Comment by nebkat** [comment]
Hi @lisn3188,

So far the master branch of esp-idf has been used but I am now transitioning to tracking v4.1, which is currently at [beta2](https://github.com/espressif/esp-idf/releases/tag/v4.1-beta2).

Best Regards,
Nebojsa
