### ISSUE TITLE
build with esp idf tools

### ISSUE THREAD

**Issue by seppalju** [nebkat/esp32-xbee#3]
Hi nebkat
I am trying to build esp32-xbee with esp idf tools in Ubuntu but facing problem as follows.

../main/main.c:30:10: fatal error: button.h: No such file or directory
 #include "button.h"
          ^~~~~~~~~~
compilation terminated.
[819/867] Building C object esp-idf/ma...iles/__idf_main.dir/ntrip_caster.c.obj
ninja: build stopped: subcommand failed.
ninja failed with exit code 1

**Comment by nebkat** [comment]
Hi seppalju,

You must run `git submodule update --init` to sync the esp32-button repository.
