### ISSUE TITLE
Compiling esp32-xbee - button.h missing

### ISSUE THREAD

**Issue by MichaelEFlip** [nebkat/esp32-xbee#31]
I tried compiling the esp32-xbee project by myself, but the button.h (and probably button.c) are missing.
Tried to find the component in the internet, the most similar was https://github.com/craftmetrics/esp32-button.

But this library has no "duration" property. After removing the access to the "duration" property the esp32-xbee project could be compiled.

It would be nice if you could add this missing components to the project or give a hint where to find them. Thank you!

**Comment by nebkat** [comment]
It is in the repository as a git submodule, if you run `git submodule update --init --recursive` it will sync. Also here https://github.com/nebkat/esp32-button

**Comment by MichaelEFlip** [comment]
Thanks for the hint, I think I did a wrong checkout. It is working now.
