### ISSUE TITLE
TLS connection to Server/Caster and Client

### ISSUE THREAD

**Issue by hagre** [nebkat/esp32-xbee#6]
Are you planing to provide a secure (TLS) NTRIP connection with NTRIP2_client.c  and NTRIP2_server.c?
Would be a very interresting feature for me.

thank you for your great work on this projekt already!

**Comment by nebkat** [comment]
I believe it would be supported already, I have just not yet enabled NTRIPv2. Ideally the ESP-IDF HTTP client would support non-standard responses that are used in NTRIPv1 so both could operate with the same code but for now that isn't possible, so v2 is disabled.
